name: PR comment
on: issue_comment

jobs:
  pr_commented:
    name: PR comment workflow
    if: |
      github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: What is the pr info?
        run: |
          echo '${{ toJSON(github) }}'
      - name: Comment contains trigger
        if: contains(github.event.comment.body, 'test comment')
        uses: ./.github/actions/branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
